### ISSUE TITLE
Error doing job: Task exception was never retrieved (None)

### ISSUE THREAD

**Issue by Lk1975** [sinseman44/koolnova-BMS-Integration#12]
Hi,
I have those two errors showing every time I try to update one room. The integrations read correctly the info from the A/C when home assistant start, but then I can't modify, and it's a pity because it was working very well. I tried to reconfigured it setting the timeout to 15 seconds instead of 5 as it was before, but nothing has changed. 

those are the errors:
Logger: homeassistant
Source: custom_components/koolnova_bms/sensor.py:149
integration: Koolnova BMS Modbus RS485 ([documentation](https://github.com/sinseman44/koolnova-BMS-Integration), [issues](https://github.com/sinseman44/koolnova-BMS-Integration/issues))
First occurred: 10:50:23 PM (1 occurrences)
Last logged: 10:50:23 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/koolnova_bms/sensor.py", line 149, in _handle_coordinator_update
    for _cur_engine in self.coordinator.data['engines']:
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

Second:
Logger: custom_components.koolnova_bms.coordinator
Source: helpers/update_coordinator.py:354
integration: Koolnova BMS Modbus RS485 ([documentation](https://github.com/sinseman44/koolnova-BMS-Integration), [issues](https://github.com/sinseman44/koolnova-BMS-Integration/issues))
First occurred: 10:50:23 PM (3 occurrences)
Last logged: 10:51:23 PM

Unexpected error fetching koolnova_bms data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/koolnova_bms/koolnova/device.py", line 408, in async_update_all_areas
    self._areas[_idx].order_temp = v['order_temp']
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/koolnova_bms/koolnova/device.py", line 126, in order_temp
    raise OrderTempError('Order temp value must be between {} and {}'.format(const.MIN_TEMP_ORDER, const.MAX_TEMP_ORDER))
custom_components.koolnova_bms.koolnova.device.OrderTempError: Order temp value must be between 15.0 and 35.0

Thanks in advance

**Comment by Lk1975** [comment]
Hi, thanks for your prompt reply. The integration was working fine, but
since I use it mostly in summer, I don't know since when it's not working.
The only thing I modify is the rooms names.
I've done the modification suggested, this is the error:
Log details (ERROR)
This error originated from a custom integration.

Logger: custom_components.koolnova_bms.coordinator
Source: helpers/update_coordinator.py:382
integration: Koolnova BMS Modbus RS485 (documentation
<https://github.com/sinseman44/koolnova-BMS-Integration>, issues
<https://github.com/sinseman44/koolnova-BMS-Integration/issues>)
First occurred: 12:44:53 PM (9 occurrences)
Last logged: 12:48:53 PM
Unexpected error fetching koolnova_bms data

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py",
line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py",
line 279, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/koolnova_bms/koolnova/device.py",
line 408, in async_update_all_areas
    self._areas[_idx].order_temp = v['order_temp']
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/koolnova_bms/koolnova/device.py",
line 126, in order_temp
    raise OrderTempError('Order temp value ({}) must be between {} and
{}'.format(val, const.MIN_TEMP_ORDER, const.MAX_TEMP_ORDER))
custom_components.koolnova_bms.koolnova.device.OrderTempError: Order
temp value (0.0) must be between 15.0 and 35.0

I see that there is one room at 0 degree.So there is probably an issue
on my koolnova System. This evening I will perform a reset and I will
let you know.



Il giorno lun 11 nov 2024 alle ore 09:28 sinseman44 <
***@***.***> ha scritto:

**Comment by Lk1975** [comment]
Hi,

I found the issue, very easy. One of my wired thermostat was not properly fitted in, so it was reading zero degrees from that room, that was causing the errors. Once I’ve reinstalled it correctly and rebooted home assistant everything started to work again.

Maybe you could add an exception to consider this kind of issue. If one thermostat is removed all the system is down.

thanks
