### ISSUE TITLE
Error reported by HomeAssistant (logs included) while starting Koolnova

### ISSUE THREAD

**Issue by ChrysMa** [sinseman44/koolnova-BMS-Integration#13]
Hello,
I recently restarted HAOS and I got this error reported in the Logs.
I am (far) away from HAOS box, but pretty sure :
- it was not unplugged (it's just a cold restart)
- Modbus still working right now (only HAOS was restarted)
So what's up ?
 

`Enregistreur: custom_components.koolnova_bms.coordinator
Source: helpers/update_coordinator.py:382
intégration: Koolnova BMS ([documentation](https://github.com/sinseman44/koolnova-BMS-Integration), [problèmes](https://github.com/sinseman44/koolnova-BMS-Integration/issues))
S'est produit pour la première fois: 11:15:54 (1 occurrences)
Dernier enregistrement: 11:15:54
Unexpected error fetching koolnova_bms data

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 279, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/koolnova_bms/koolnova/device.py", line 394, in async_update_all_areas
    _ret, _vals = await self._client.async_areas_registered()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/koolnova_bms/koolnova/operations.py", line 202, in async_areas_registered
    regs, ret = await self.__async_read_registers(start_reg = const.REG_START_ZONE,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/koolnova_bms/koolnova/operations.py", line 92, in __async_read_registers
    raise ModbusConnexionError('Client Modbus not connected')
custom_components.koolnova_bms.koolnova.operations.ModbusConnexionError: Client Modbus not connected`

**Comment by sinseman44** [comment]
Hi ChrysMa,

It seems that the integration can no longer communicate with your USB/Modbus controller. Did it change location on reboot. Check if your ttyUSBx is still active on your HAOS box and is the same as declared in the integration ? If all is correct, try to remove  the integration and retry to configure it.

**Comment by ChrysMa** [comment]
Hi,
This error was reported by HA after a reboot (needed for the scheduler upgrade). I DID NOT touch/modify anything. The USB is still working since then (I can see the climate and modify temp/ heat on/off and so on). I am away from the HA box hence I cannot unplug/plug anything.
All is correct but this... So I will try to remove/add koolnova-BMS-integration
