### ISSUE TITLE
ModbusConnexionError: Client Modbus not connected`

### ISSUE THREAD

**Issue by ChrysMa** [sinseman44/koolnova-BMS-Integration#18]
Hello
AFAIK since the release 0.2.0, the below error is reported in HA logs. I experience now often unreadable zone status never noticed before....

`Enregistreur: custom_components.koolnova_bms.coordinator
Source: helpers/update_coordinator.py:382
intégration: Koolnova BMS ([documentation](https://github.com/sinseman44/koolnova-BMS-Integration), [problèmes](https://github.com/sinseman44/koolnova-BMS-Integration/issues))
S'est produit pour la première fois: 19 novembre 2024 à 20:39:02 (374 occurrences)
Dernier enregistrement: 22:15:47
Unexpected error fetching koolnova_bms data

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 279, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/koolnova_bms/koolnova/device.py", line 431, in async_update_all_areas
    _ret, _vals = await self._client.async_areas_registered()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/koolnova_bms/koolnova/operations.py", line 212, in async_areas_registered
    regs, ret = await self.__async_read_registers(start_reg = const.REG_START_ZONE,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/koolnova_bms/koolnova/operations.py", line 101, in __async_read_registers
    raise ModbusConnexionError('Client Modbus not connected')
custom_components.koolnova_bms.koolnova.operations.ModbusConnexionError: Client Modbus not connected`

**Comment by sinseman44** [comment]
Hi,

Nothing has changed in the operation of RTU mode between version 0.1.3 and the latest version 0.2.0.
You can try to change default extra parameters (**reconnect_delay**, **reconnect_delay_max**  and **retries**) in the initialisation of ModbusClient in the file `koolnova/operations.py` (line 49)
* _reconnect_delay_: Minimum delay in seconds.milliseconds before reconnecting (default: 0.1)
* _reconnect_delay_max_: Maximum delay in seconds.milliseconds before reconnecting. (default: 300)
* _retries_: Max number of retries per request (default: 3)
```
self._client = ModbusClient(port=self._rtu_port,
                            baudrate=self._rtu_baudrate,
                            parity=self._rtu_parity,
                            stopbits=self._rtu_stopbits,
                            bytesize=self._rtu_bytesize,
                            timeout=self._timeout)
```
by
```
self._client = ModbusClient(port=self._rtu_port,
                            baudrate=self._rtu_baudrate,
                            parity=self._rtu_parity,
                            stopbits=self._rtu_stopbits,
                            bytesize=self._rtu_bytesize,
                            timeout=self._timeout,
                            reconnect_delay=0.1,
                            reconnect_delay_max=500,
                            retries=5)
```
Restart your Home Assistant and check if this improves the integration behavior.

**Comment by ChrysMa** [comment]
Hi,
Thanks. Code updated...
Got immediate result (after reboot) 

`
Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.koolnova_bms.koolnova.operations
Source: custom_components/koolnova_bms/koolnova/operations.py:89
intégration: Koolnova BMS (documentation, problèmes)
S'est produit pour la première fois: 11:35:55 (29 occurrences)
Dernier enregistrement: 11:40:03

Modbus Error: Modbus Error: [Connection] Connection lost during request
Modbus Error: 'NoneType' object has no attribute 'close'
Modbus Error: Modbus Error: [Input/Output] ERROR: No response received after 5 retries
`

Doesn't seem better...

**Comment by ChrysMa** [comment]
OK after a while and many tests .
Tried to restart / modify USB port and so on : no better result

Then I plugged the USB dongle directly onto a desktop ran many tests : 
- on the windows desktop : powerhud modbus tester on port COM3 (linked) : run thousand of read first at 1000ms poll rate down to 100ms (no less). Reported no error reading offset 48 then 40001 (tried many) - got the expected values from the Koolnova unit
- on the linux desktop (got many computer here) : tried modbus (cf jpelletier) : no problem either
- back on my homeassistant server (which is a proxmox with an haos vm) : on the root node unkinked the USB port and locally ran mbpoll read
`
mbpoll -b 9600 -p even -d 8 -s 1 -m rtu -t 4 -a 49 -r 40001 -c 16 -l 100 /dev/ttyUSB0
`
low error reported
`
--- /dev/ttyUSB0 poll statistics ---
605 frames transmitted, 605 received, 0 errors, 0.0% frame loss

everything was closed.
Have a nice day !
`
highest error reporter was less than 0.3% over more than 10000 requests
- so then after erasing all previous koolnova plugin, restarted HA, then I connected the dongle back to HA USB... reinstalled koolnova BMS plugin and .... tada !!.... hundred of errors again.

So I keep searchin' ;-)

**Comment by sinseman44** [comment]
it's incomprehensible!
My opinion is that you must have a problem with the HA/pymodbus couple.
In your test cases, you did not test other clients on the HAOS VM. You also did not try to use the Koolnova integration on a Linux machine (Desktop). Can you try to import the koolnova BMS python wrapper (device.py) in a virtual python app (virtualenv) in a Linux desktop (not HAOS) with the same environment.txt ("pymodbus==3.5.4", "pyserial==3.5") ?

**Comment by sinseman44** [comment]
You can also try to install the [latest](https://pypi.org/project/pymodbus) (3.7.4) version of pymodbus in your HAOS VM.
Change the manifest.json in the koolnova integration package with it. Restart HA.
```
{
    "domain": "koolnova_bms",
    "name": "Koolnova BMS Modbus RS485",
    "codeowners": ["@sinseman44"],
    "config_flow": true,
    "documentation": "https://github.com/sinseman44/koolnova-BMS-Integration",
    "issue_tracker": "https://github.com/sinseman44/koolnova-BMS-Integration/issues",
    "integration_type": "device",
    "iot_class": "local_polling",
    "quality_scale": "silver",
    "loggers": ["koolnova"],
    "requirements": [
	"pymodbus==3.7.4",
	"pyserial==3.5"
    ],
    "version": "0.2.1"
}
```

**Comment by ChrysMa** [comment]
Ok got it. Will be my next move. 
Right now I am under test with below params 
`
            self._client = ModbusClient(port=self._rtu_port,
                                        baudrate=self._rtu_baudrate,
                                        parity=self._rtu_parity,
                                        stopbits=self._rtu_stopbits,
                                        bytesize=self._rtu_bytesize,
                                        timeout=self._timeout,
                                        reconnect_delay=0.2,
                                        reconnect_delay_max=500,
                                        retries=5)
`
Got not any reported error... 

Probably related to underlying software... pymodbus or...

**Comment by ChrysMa** [comment]
ImportError: cannot import name 'ModbusRtuFramer' from 'pymodbus.transaction' (/usr/local/lib/python3.12/site-packages/pymodbus/transaction.py)

**Comment by ChrysMa** [comment]
After 48h : this seems to solve the reported issue. 
I think we can close it as soon as the integration switch to latest pymodbus releas ;-)

**Comment by Lk1975** [comment]
Using your integration together with Huawai solar integration it goes in error, because huawai solar integration use pymodbus version 3.6.9 and yours instead version 3.7.4. Would it be possible to run it using version 3.6.9?
