### ISSUE TITLE
 Unexpected error fetching koolnova_bms data 

### ISSUE THREAD

**Issue by Gilles-Clemenceau** [sinseman44/koolnova-BMS-Integration#9]
Hi,
The koolnova entities are often "Not available" & then come back from time to time.
I have 2 errors in the logs. I just want to know if I need to go up there check the cable or not ^^'

```

Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.koolnova_bms.coordinator
Source: helpers/update_coordinator.py:354
intégration: Koolnova BMS (documentation, problèmes)
S'est produit pour la première fois: 19 octobre 2024 à 20:50:36 (1512 occurrences)
Dernier enregistrement: 09:17:43

Unexpected error fetching koolnova_bms data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/koolnova_bms/koolnova/device.py", line 394, in async_update_all_areas
    _ret, _vals = await self._client.async_areas_registered()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/koolnova_bms/koolnova/operations.py", line 205, in async_areas_registered
    raise ReadRegistersError("Error reading holding register")
custom_components.koolnova_bms.koolnova.operations.ReadRegistersError: Error reading holding register
```

```
Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.koolnova_bms.coordinator
Source: helpers/update_coordinator.py:354
intégration: Koolnova BMS (documentation, problèmes)
S'est produit pour la première fois: 19 octobre 2024 à 20:50:36 (1512 occurrences)
Dernier enregistrement: 09:17:43

Unexpected error fetching koolnova_bms data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/koolnova_bms/koolnova/device.py", line 394, in async_update_all_areas
    _ret, _vals = await self._client.async_areas_registered()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/koolnova_bms/koolnova/operations.py", line 205, in async_areas_registered
    raise ReadRegistersError("Error reading holding register")
custom_components.koolnova_bms.koolnova.operations.ReadRegistersError: Error reading holding register
```

**Comment by sinseman44** [comment]
Hi Gilles,
Thanks to report your error.

Can you active debug mode (see README) to have a better understanding of the problem ?
At first sight, the modbus operations (read and write) timeout (default: 5 secondes) might occur when the koolnova integration try to updates all values (polling interval : 30secondes).
Can you reconfigure your koolnova Integration and increase the timeout value in the the configuration first page to see if error desepear ?

**Comment by Gilles-Clemenceau** [comment]
It seems that setting the timeout with 15 seconds has solved my bug.
